version: '3'
  #  volumes:
  # data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: [postgres]
# services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: pass123



   